name: Stockfish
on:
  push:
    branches:
      - master
      - tools
      - github_ci
  pull_request:
    branches:
      - master
      - tools
jobs:
  Sanitizers:
    uses: ./.github/workflows/stockfish_sanitizers.yml
  Tests:
    uses: ./.github/workflows/stockfish_test.yml
  Compiles:
    uses: ./.github/workflows/stockfish_compile_test.yml
  Binaries:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/stockfish_binaries.yml
  ARM_Binaries:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/stockfish_arm_binaries.yml
